-- 建表
create table public.user_configs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  data json null,
  updated_at timestamp with time zone null,
  user_id uuid not null,
  last_device_id text null, -- 1.3.5 新增
  constraint user_configs_pkey primary key (id),
  constraint user_configs_user_id_key unique (user_id)
) TABLESPACE pg_default;

-- 启用行级安全（RLS）
alter table public.user_configs enable row level security;

drop policy if exists "user_configs_select_own" on public.user_configs;
drop policy if exists "user_configs_insert_own" on public.user_configs;
drop policy if exists "user_configs_update_own" on public.user_configs;

create policy "user_configs_select_own"
on public.user_configs
for select
using (auth.uid() = user_id);

create policy "user_configs_insert_own"
on public.user_configs
for insert
with check (auth.uid() = user_id);

create policy "user_configs_update_own"
on public.user_configs
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- 全量更新函数
create or replace function public.update_user_config_full(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
returns void
language plpgsql
security definer
set search_path = public
as
$$
declare
  current_device_id text;
begin
  select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  insert into public.user_configs (user_id, data, updated_at, last_device_id)
  values (auth.uid(), payload::json, now(), p_last_device_id)
  on conflict (user_id) do update
  set data = excluded.data,
      updated_at = excluded.updated_at,
      last_device_id = coalesce(excluded.last_device_id, public.user_configs.last_device_id);
end;
$$;

grant execute on function public.update_user_config_full(jsonb, text, boolean) to authenticated;
grant execute on function public.update_user_config_full(jsonb, text, boolean) to service_role;

-- 增量更新函数
create or replace function public.update_user_config_partial(payload jsonb, p_last_device_id text default null, p_force_takeover boolean default false)
returns void
language plpgsql
security definer
set search_path = public
as
$$
declare
  current_device_id text;
begin
  select last_device_id into current_device_id from public.user_configs where user_id = auth.uid();

  if current_device_id is not null and p_last_device_id is not null and current_device_id != p_last_device_id and not p_force_takeover then
    raise exception 'DEVICE_CONFLICT: Logged in on another device';
  end if;

  update public.user_configs
  set data = ((coalesce(data::jsonb, '{}'::jsonb) || payload)::json),
      updated_at = now(),
      last_device_id = coalesce(p_last_device_id, last_device_id)
  where user_id = auth.uid();
end;
$$;

grant execute on function public.update_user_config_partial(jsonb, text, boolean) to authenticated;
grant execute on function public.update_user_config_partial(jsonb, text, boolean) to service_role;

-- v1.0.0 版本更新关联板块表

-- 创建 fund_related 表
create table public.fund_related (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  fund_code character varying null,
  related_sector text null,
  constraint fund_related_pkey primary key (id),
  constraint fund_related_fund_code_key unique (fund_code)
) TABLESPACE pg_default;

-- 1. 开启 RLS
ALTER TABLE fund_related ENABLE ROW LEVEL SECURITY;

-- 2. 仅允许已登录用户查询
CREATE POLICY "Allow authenticated users to select fund_related"
ON fund_related
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);

-- 创建 fund_secid 表
create table public.fund_secid (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  related_sector text null,
  secid character varying null,
  constraint fund_secid_pkey primary key (id)
) TABLESPACE pg_default;

-- 1. 开启 RLS
ALTER TABLE fund_secid ENABLE ROW LEVEL SECURITY;

-- 2. 仅允许已登录用户查询
CREATE POLICY "Allow authenticated users to select fund_secid"
ON fund_secid
FOR SELECT
TO authenticated
USING (auth.uid() IS NOT NULL);
